name: Testing with devbox

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0

      - name: Run arbitrary commands
        run: devbox run -- echo "No ar!"

      - name: Run a script called run_test
        run: devbox run run_test
